module.exports = {
  apps: [
    {
      name: 'fences-app',
      script: 'npx',
      args: 'next start -p 3001',
      cwd: '/root/Fences-of-the-curtain',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '1G',
      kill_timeout: 15000,
      wait_ready: true,
      listen_timeout: 30000,
      min_uptime: '10s',
      max_restarts: 5,
      restart_delay: 5000,
      exp_backoff_restart_delay: 200,
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/var/log/fences-app/error.log',
      out_file: '/var/log/fences-app/out.log',
      merge_logs: true,
      time: true,
      autorestart: true,
      watch: false,
    },
  ],
};
