module.exports = {
  apps: [
    {
      name: 'fences-app',
      script: 'npx',
      args: 'next start -p 3000',
      cwd: '/root/Fences-of-the-curtain',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '1G',
      kill_timeout: 15000,
      wait_ready: true,
      listen_timeout: 30000,
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4000,
      exp_backoff_restart_delay: 100,
      env_production: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/var/log/fences-app/error.log',
      out_file: '/var/log/fences-app/out.log',
      merge_logs: true,
      log_file: '/var/log/fences-app/combined.log',
      time: true,
      autorestart: true,
      watch: false,
      ignore_watch: [
        'node_modules',
        'logs',
        '.git',
        '.next',
        'coverage',
      ],
      watch_delay: 1000,
      env: {
        NODE_ENV: 'production',
      },
    },
  ],
};
