import { PrismaClient, TrussProfileCategory } from '@prisma/client';

const prisma = new PrismaClient();

async function seedTrussProfiles() {
  const profiles = [
    {
      name: '80×80×2',
      category: TrussProfileCategory.POST,
      sectionWidth: 80,
      sectionHeight: 80,
      wallThickness: 2,
      sectionArea: 6.03,
      momentOfInertiaX: 56.4,
      momentOfInertiaY: 56.4,
      sectionModulusX: 14.1,
      sectionModulusY: 14.1,
      radiusOfGyrationX: 3.06,
      radiusOfGyrationY: 3.06,
      weightPerMeter: 4.84,
      retailPricePerMeter: 540,
      purchasePricePerMeter: 420,
      priority: 1,
    },
    {
      name: '100×100×2',
      category: TrussProfileCategory.POST,
      sectionWidth: 100,
      sectionHeight: 100,
      wallThickness: 2,
      sectionArea: 7.64,
      momentOfInertiaX: 114.1,
      momentOfInertiaY: 114.1,
      sectionModulusX: 22.82,
      sectionModulusY: 22.82,
      radiusOfGyrationX: 3.87,
      radiusOfGyrationY: 3.87,
      weightPerMeter: 6.10,
      retailPricePerMeter: 680,
      purchasePricePerMeter: 540,
      priority: 2,
    },
    {
      name: '100×100×3',
      category: TrussProfileCategory.POST,
      sectionWidth: 100,
      sectionHeight: 100,
      wallThickness: 3,
      sectionArea: 11.25,
      momentOfInertiaX: 165.0,
      momentOfInertiaY: 165.0,
      sectionModulusX: 33.0,
      sectionModulusY: 33.0,
      radiusOfGyrationX: 3.83,
      radiusOfGyrationY: 3.83,
      weightPerMeter: 8.96,
      retailPricePerMeter: 950,
      purchasePricePerMeter: 760,
      priority: 3,
    },
    {
      name: '120×120×3',
      category: TrussProfileCategory.POST,
      sectionWidth: 120,
      sectionHeight: 120,
      wallThickness: 3,
      sectionArea: 13.65,
      momentOfInertiaX: 296.0,
      momentOfInertiaY: 296.0,
      sectionModulusX: 49.3,
      sectionModulusY: 49.3,
      radiusOfGyrationX: 4.65,
      radiusOfGyrationY: 4.65,
      weightPerMeter: 10.84,
      retailPricePerMeter: 1150,
      purchasePricePerMeter: 920,
      priority: 4,
    },
    {
      name: '120×120×4',
      category: TrussProfileCategory.POST,
      sectionWidth: 120,
      sectionHeight: 120,
      wallThickness: 4,
      sectionArea: 17.80,
      momentOfInertiaX: 378.0,
      momentOfInertiaY: 378.0,
      sectionModulusX: 63.0,
      sectionModulusY: 63.0,
      radiusOfGyrationX: 4.61,
      radiusOfGyrationY: 4.61,
      weightPerMeter: 14.20,
      retailPricePerMeter: 1500,
      purchasePricePerMeter: 1200,
      priority: 5,
    },
    {
      name: '60×40×2',
      category: TrussProfileCategory.CROSSBEAM,
      sectionWidth: 60,
      sectionHeight: 40,
      wallThickness: 2,
      sectionArea: 3.74,
      momentOfInertiaX: 18.7,
      momentOfInertiaY: 9.8,
      sectionModulusX: 6.23,
      sectionModulusY: 4.9,
      radiusOfGyrationX: 2.24,
      radiusOfGyrationY: 1.62,
      weightPerMeter: 2.93,
      retailPricePerMeter: 340,
      purchasePricePerMeter: 270,
      priority: 1,
    },
    {
      name: '60×40×2.5',
      category: TrussProfileCategory.CROSSBEAM,
      sectionWidth: 60,
      sectionHeight: 40,
      wallThickness: 2.5,
      sectionArea: 4.60,
      momentOfInertiaX: 22.7,
      momentOfInertiaY: 11.8,
      sectionModulusX: 7.56,
      sectionModulusY: 5.9,
      radiusOfGyrationX: 2.22,
      radiusOfGyrationY: 1.60,
      weightPerMeter: 3.60,
      retailPricePerMeter: 400,
      purchasePricePerMeter: 320,
      priority: 2,
    },
    {
      name: '80×40×2.5',
      category: TrussProfileCategory.CROSSBEAM,
      sectionWidth: 80,
      sectionHeight: 40,
      wallThickness: 2.5,
      sectionArea: 5.60,
      momentOfInertiaX: 43.6,
      momentOfInertiaY: 13.1,
      sectionModulusX: 10.9,
      sectionModulusY: 6.55,
      radiusOfGyrationX: 2.79,
      radiusOfGyrationY: 1.53,
      weightPerMeter: 4.52,
      retailPricePerMeter: 510,
      purchasePricePerMeter: 410,
      priority: 3,
    },
    {
      name: '80×60×3',
      category: TrussProfileCategory.CROSSBEAM,
      sectionWidth: 80,
      sectionHeight: 60,
      wallThickness: 3,
      sectionArea: 7.65,
      momentOfInertiaX: 61.4,
      momentOfInertiaY: 38.5,
      sectionModulusX: 15.35,
      sectionModulusY: 12.83,
      radiusOfGyrationX: 2.83,
      radiusOfGyrationY: 2.24,
      weightPerMeter: 6.20,
      retailPricePerMeter: 690,
      purchasePricePerMeter: 550,
      priority: 4,
    },
    {
      name: '40×40×1.5',
      category: TrussProfileCategory.STRUT,
      sectionWidth: 40,
      sectionHeight: 40,
      wallThickness: 1.5,
      sectionArea: 2.23,
      momentOfInertiaX: 5.3,
      momentOfInertiaY: 5.3,
      sectionModulusX: 2.65,
      sectionModulusY: 2.65,
      radiusOfGyrationX: 1.54,
      radiusOfGyrationY: 1.54,
      weightPerMeter: 1.75,
      retailPricePerMeter: 220,
      purchasePricePerMeter: 170,
      priority: 1,
    },
    {
      name: '40×40×2',
      category: TrussProfileCategory.STRUT,
      sectionWidth: 40,
      sectionHeight: 40,
      wallThickness: 2,
      sectionArea: 2.94,
      momentOfInertiaX: 6.82,
      momentOfInertiaY: 6.82,
      sectionModulusX: 3.41,
      sectionModulusY: 3.41,
      radiusOfGyrationX: 1.52,
      radiusOfGyrationY: 1.52,
      weightPerMeter: 2.31,
      retailPricePerMeter: 270,
      purchasePricePerMeter: 210,
      priority: 2,
    },
    {
      name: '40×40×2.5',
      category: TrussProfileCategory.STRUT,
      sectionWidth: 40,
      sectionHeight: 40,
      wallThickness: 2.5,
      sectionArea: 3.60,
      momentOfInertiaX: 8.13,
      momentOfInertiaY: 8.13,
      sectionModulusX: 4.07,
      sectionModulusY: 4.07,
      radiusOfGyrationX: 1.50,
      radiusOfGyrationY: 1.50,
      weightPerMeter: 2.85,
      retailPricePerMeter: 320,
      purchasePricePerMeter: 250,
      priority: 3,
    },
    {
      name: '50×50×2',
      category: TrussProfileCategory.STRUT,
      sectionWidth: 50,
      sectionHeight: 50,
      wallThickness: 2,
      sectionArea: 3.74,
      momentOfInertiaX: 13.71,
      momentOfInertiaY: 13.71,
      sectionModulusX: 5.48,
      sectionModulusY: 5.48,
      radiusOfGyrationX: 1.92,
      radiusOfGyrationY: 1.92,
      weightPerMeter: 2.93,
      retailPricePerMeter: 340,
      purchasePricePerMeter: 270,
      priority: 4,
    },
    {
      name: '40×40×2',
      category: TrussProfileCategory.ARCH,
      sectionWidth: 40,
      sectionHeight: 40,
      wallThickness: 2,
      sectionArea: 2.94,
      momentOfInertiaX: 6.82,
      momentOfInertiaY: 6.82,
      sectionModulusX: 3.41,
      sectionModulusY: 3.41,
      radiusOfGyrationX: 1.52,
      radiusOfGyrationY: 1.52,
      weightPerMeter: 2.31,
      retailPricePerMeter: 270,
      purchasePricePerMeter: 210,
      priority: 1,
    },
    {
      name: '40×40×2.5',
      category: TrussProfileCategory.ARCH,
      sectionWidth: 40,
      sectionHeight: 40,
      wallThickness: 2.5,
      sectionArea: 3.60,
      momentOfInertiaX: 8.13,
      momentOfInertiaY: 8.13,
      sectionModulusX: 4.07,
      sectionModulusY: 4.07,
      radiusOfGyrationX: 1.50,
      radiusOfGyrationY: 1.50,
      weightPerMeter: 2.85,
      retailPricePerMeter: 320,
      purchasePricePerMeter: 250,
      priority: 2,
    },
    {
      name: '40×40×3',
      category: TrussProfileCategory.ARCH,
      sectionWidth: 40,
      sectionHeight: 40,
      wallThickness: 3,
      sectionArea: 4.23,
      momentOfInertiaX: 9.26,
      momentOfInertiaY: 9.26,
      sectionModulusX: 4.63,
      sectionModulusY: 4.63,
      radiusOfGyrationX: 1.48,
      radiusOfGyrationY: 1.48,
      weightPerMeter: 3.36,
      retailPricePerMeter: 380,
      purchasePricePerMeter: 300,
      priority: 3,
    },
    {
      name: '60×40×2',
      category: TrussProfileCategory.ARCH,
      sectionWidth: 60,
      sectionHeight: 40,
      wallThickness: 2,
      sectionArea: 3.74,
      momentOfInertiaX: 18.7,
      momentOfInertiaY: 9.8,
      sectionModulusX: 6.23,
      sectionModulusY: 4.9,
      radiusOfGyrationX: 2.24,
      radiusOfGyrationY: 1.62,
      weightPerMeter: 2.93,
      retailPricePerMeter: 340,
      purchasePricePerMeter: 270,
      priority: 4,
    },
  ];

  for (const profile of profiles) {
    const existing = await prisma.trussProfileType.findFirst({
      where: {
        category: profile.category,
        sectionWidth: profile.sectionWidth,
        sectionHeight: profile.sectionHeight,
        wallThickness: profile.wallThickness,
      },
    });
    if (existing) {
      console.log(`[SKIP] TrussProfile ${profile.name} (${profile.category})`);
      continue;
    }
    await prisma.trussProfileType.create({ data: profile });
    console.log(`[CREATED] TrussProfile ${profile.name} (${profile.category})`);
  }
}

async function seedTrussRoofCoverings() {
  const coverings = [
    {
      name: 'Металлочерепица (0.5 мм)',
      weightPerSqm: 5.0,
      thickness: 0.5,
      width: 1180,
      usefulWidth: 1100,
      standardLength: 4000,
      coating: 'Полиэстер',
      color: 'Разные',
      retailPricePerSqm: 650,
      purchasePricePerSqm: 500,
      priority: 1,
    },
    {
      name: 'Поликарбонат 8 мм',
      weightPerSqm: 1.5,
      thickness: 8,
      width: 2100,
      usefulWidth: 2000,
      standardLength: 6000,
      coating: 'UV-защита',
      color: 'Прозрачный / Бронза',
      retailPricePerSqm: 480,
      purchasePricePerSqm: 360,
      priority: 2,
    },
    {
      name: 'Поликарбонат 10 мм',
      weightPerSqm: 1.7,
      thickness: 10,
      width: 2100,
      usefulWidth: 2000,
      standardLength: 6000,
      coating: 'UV-защита',
      color: 'Прозрачный / Бронза',
      retailPricePerSqm: 580,
      purchasePricePerSqm: 440,
      priority: 3,
    },
    {
      name: 'Поликарбонат 16 мм',
      weightPerSqm: 2.7,
      thickness: 16,
      width: 2100,
      usefulWidth: 2000,
      standardLength: 6000,
      coating: 'UV-защита',
      color: 'Прозрачный / Бронза',
      retailPricePerSqm: 820,
      purchasePricePerSqm: 620,
      priority: 4,
    },
    {
      name: 'Профнастил С21 (0.5 мм)',
      weightPerSqm: 5.4,
      thickness: 0.5,
      width: 1051,
      usefulWidth: 1000,
      standardLength: 4000,
      coating: 'Полиэстер',
      color: 'Разные',
      retailPricePerSqm: 520,
      purchasePricePerSqm: 400,
      priority: 5,
    },
  ];

  for (const covering of coverings) {
    const existing = await prisma.trussRoofCovering.findFirst({
      where: { name: covering.name },
    });
    if (existing) {
      console.log(`[SKIP] TrussRoofCovering ${covering.name}`);
      continue;
    }
    await prisma.trussRoofCovering.create({ data: covering });
    console.log(`[CREATED] TrussRoofCovering ${covering.name}`);
  }
}

async function main() {
  console.log('Seeding truss data...');
  await seedTrussProfiles();
  await seedTrussRoofCoverings();
  console.log('Truss data seeding complete.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
